-- Database Schema for Cinema Booking System

-- Drop tables if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "Booking-Ticket" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "TICKET" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "BOOKING" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "SEAT" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "SHOWTIME" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "HALL" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "CINEMA" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "MOVIE" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "PRICINGPOLICY" CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "User" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create User table
CREATE TABLE "User" (
    USER_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(50),
    USER_EMAIL VARCHAR2(60),
    USER_PHONE NUMBER,
    ADDRESS VARCHAR2(150)
);

-- Create Movie table
CREATE TABLE "MOVIE" (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(60),
    GENRE VARCHAR2(60),
    DURATION NUMBER,
    LANGUAGE VARCHAR2(60)
);

-- Create PricingPolicy table
CREATE TABLE "PRICINGPOLICY" (
    POLICY_ID NUMBER PRIMARY KEY,
    POLICY_NAME VARCHAR2(60),
    MULTIPLIER NUMBER,
    POLICY_DATE DATE,
    DESCRIPTION VARCHAR2(100)
);

-- Create Cinema table
CREATE TABLE "CINEMA" (
    THEATRE_ID NUMBER PRIMARY KEY,
    CINEMA_NAME VARCHAR2(30),
    CINEMA_LOCATION VARCHAR2(60),
    CONTACT_INFO NUMBER,
    EMAIL VARCHAR2(60)
);

-- Create Hall table
CREATE TABLE "HALL" (
    HALL_ID NUMBER PRIMARY KEY,
    HALL_NAME VARCHAR2(30),
    TOTAL_CAPACITY NUMBER,
    HALL_TYPE VARCHAR2(30),
    HALL_STATUS VARCHAR2(30),
    CINEMA_THEATRE_ID NUMBER,
    CONSTRAINT FK_HALL_CINEMA FOREIGN KEY (CINEMA_THEATRE_ID) REFERENCES "CINEMA"(THEATRE_ID) ON DELETE CASCADE
);

-- Create Seat table
CREATE TABLE "SEAT" (
    SEAT_ID NUMBER PRIMARY KEY,
    HALL_ID NUMBER,
    SEAT_ROW VARCHAR2(10),
    SEAT_COLUMN VARCHAR2(10),
    SEAT_NUMBER VARCHAR2(20),
    STATUS VARCHAR2(20),
    CONSTRAINT FK_SEAT_HALL FOREIGN KEY (HALL_ID) REFERENCES "HALL"(HALL_ID) ON DELETE CASCADE
);

-- Create Showtime table
CREATE TABLE "SHOWTIME" (
    SHOW_ID NUMBER PRIMARY KEY,
    START_TIME DATE,
    END_TIME DATE,
    SHOW_TYPE VARCHAR2(30),
    BASE_PRICE NUMBER,
    HALL_ID NUMBER,
    MOVIE_ID NUMBER,
    POLICY_ID NUMBER,
    CONSTRAINT FK_SHOWTIME_HALL FOREIGN KEY (HALL_ID) REFERENCES "HALL"(HALL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHOWTIME_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES "MOVIE"(MOVIE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHOWTIME_POLICY FOREIGN KEY (POLICY_ID) REFERENCES "PRICINGPOLICY"(POLICY_ID) ON DELETE SET NULL
);

-- Create Booking table
CREATE TABLE "BOOKING" (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    SHOWTIME_ID NUMBER,
    BOOKING_TIMESTAMP DATE DEFAULT SYSDATE,
    TOTAL_AMOUNT NUMBER,
    STATUS VARCHAR2(30),
    CONSTRAINT FK_BOOKING_USER FOREIGN KEY (USER_ID) REFERENCES "User"(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKING_SHOWTIME FOREIGN KEY (SHOWTIME_ID) REFERENCES "SHOWTIME"(SHOW_ID) ON DELETE CASCADE
);

-- Create Ticket table
CREATE TABLE "TICKET" (
    TICKET_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER,
    SEAT_ID NUMBER,
    FINAL_PRICE NUMBER,
    CONSTRAINT FK_TICKET_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES "BOOKING"(BOOKING_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TICKET_SEAT FOREIGN KEY (SEAT_ID) REFERENCES "SEAT"(SEAT_ID) ON DELETE CASCADE
);
